### ISSUE TITLE
Daily todos

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/landing-page#14]
## Mon 21st March
- [x] Swap css notes #11 
- [x] ~~Mailchimp integration #10~~ Opted for Google forms instead 
- [x] Styling for landing 
- [ ] ~~Setup test watching for TDD~~ pushed back to mvp

**Comment by minaorangina** [comment]
Mailchimp integration was swapped for: 
- [x] Google Forms

**Comment by minaorangina** [comment]
### Wednesday 23rd March
- [ ] Optimise for desktop and mobile #23 
- [ ] Hook up master to heroku
- [ ] Google analytics
